### PR TITLE
chore: Reduce the usage of Mac OS in the tests

### PR DESCRIPTION
**Pull request by jjtang1985**
It happened 5+ times (on Feb.12th) that the GH Actions cost 20+ minute, because of the waiting time of the Mac OS containers.
I guess with more people working on it, it's harder to get the containers.

In this PR, I would like to minimise the usage of the Mac OS container and only keep using one.

I disabled the combination of Mac OS and node 10, since we still have two cases below:
- Mac OS and node 12
- ubuntu and node 10 

Let me know your opinion.

### CODE REVIEW

**Comment by FrankEssenberger** [comment]
For me it is fine to just use one mac container. In general I would prefer to have also one windows container in the mix, because mac should be more like unix so, but windows is real different.

**Comment by jjtang1985** [comment]
> In general I would prefer to have also one windows container in the mix, because mac should be more like unix so, but windows is real different.

For windows, we have a separate ticket, because we have to fix something before enabling. Also, windows is slower than Mac OS and ubuntu, which needs to be evaluated again.

**Review by FrankEssenberger — APPROVED** [review]
LGTM

**Review by marikaner — APPROVED** [review]
Agreed.

**Pull request merged**
