### PR TITLE
chore: Implement Blackduck retry logic

### PR DESCRIPTION
**Pull request by tomfrenken**
This PR implements a very simple retry logic for our Blackduck scans, as it seems we hit a performance limit with dependabot's PRs, because they are all opened simultaneously.

This should hopefully be fixed with a simple retry.

### CODE REVIEW

**Review by jjtang1985 — COMMENTED** [review]
I feel this will not work. All the failing pipeline will start together, after 1 min.

**Comment by tomfrenken** [comment]
> I feel this will not work. All the failing pipeline will start together, after 1 min.

Yes, however I think not all pipelines fail, only a fraction, and that fraction will then restart together after 1 minute

**Comment by tomfrenken** [comment]
This could potentially still hit the performance threshold though I guess 🤔

**Review by jjtang1985 — APPROVED** [review]
Let's merge and test it, so we have some statistics.

**Comment by tomfrenken** [comment]
Related to SAP/cloud-sdk-backlog#574.

**Pull request merged**
