### PR TITLE
Remove references to defunct npm registry and deprecate npmrc cli option

### PR DESCRIPTION
**Pull request by fwilhe**

### CODE REVIEW

**Comment by fwilhe** [comment]
Should we remove the "generate npmrc option" completely?

**Review by FrankEssenberger — APPROVED** [review]
[q] Could we remove the method completely?

**Comment by florian-richter** [comment]
I agree we should remove the option completely

**Comment by fwilhe** [comment]
Can we really just delete the option? It is listed as 'deprecated' in the `--help` output, but imo this would technically be a breaking change..

```
      --generateNpmrc                Deprecated. If set to true the generator
                                     will generate an .npmrc file specifying a
                                     registry for @sap scoped dependencies. This
                                     is not necessary anymore and will be
                                     skipped by default.
```

**Comment by fwilhe** [comment]
> I think it was internal so removing is possible.

"internal" in what sense? The `npmrc` function has an `@internal` annotation, is this what you mean? What's the (semantic) meaning of this? It does not refer to the cli option in any way, does it?

**Comment by FrankEssenberger** [comment]
> "internal" in what sense? The `npmrc` function has an `@internal` annotation, is this what you mean? What's the (semantic) meaning of this? It does not refer to the cli option in any way, does it?

This means that the method is not exported on root level and is not part of our public API. This means we can refactor, rename or delete methods like this as we please. Sometime we add a compatibility note but this is not needed in this case.

**Review by FrankEssenberger — APPROVED** [review]

**Pull request merged**
