### PR TITLE
refractor!: remove deprecated functionality

### PR DESCRIPTION
**Pull request by tomfrenken**
Removes the majority of deprecated functions/properties etc.
Solves some `TO-DO` comments

Closes SAP/cloud-sdk-backlog#194.

### CODE REVIEW

**Comment by FrankEssenberger** [comment]
General comment: make smaller PRs with chunks of things removed. E.g. deprecated, then some TODOs and so on.

**Comment by tomfrenken** [comment]
Yes agreed, I think i only have one TO-DO in this PR, because it was intertwined with one of the deprecation removals

**Review by FrankEssenberger — APPROVED** [review]
LGTM

**Comment by FrankEssenberger** [comment]
There were folders named `legacy` are they also deleted already?

**Comment by tomfrenken** [comment]
I have a few PR's lined up that remove them, they are TODOs that's why they are not in here

**Pull request merged**
